### ISSUE TITLE
Can't test file uploads

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALKilnInThePlayground#18]
```
WARNING: You can store files to upload in 'docassemble//data/source'. These tests could not find a folder like that. The current directory is  /tmp; is that in the top level folder of your docassemble package? (X)?

ERROR: Error occurred when tried to answer fields on question "file-upload-screen".

**-- Scenario Failed --**
```

Tried testing the ALWeaver in the playground and got this error.

Also:    
```
Error: ENOENT: no such file or directory, access '/tmp/docassemble'
           at Object.accessSync (fs.js:208:3)
           at Object.uploadFiles (/var/www/.npm-global/lib/node_modules/@suffolklitlab/alkiln/lib/scope.js:1767:10)
           at Object.input (/var/www/.npm-global/lib/node_modules/@suffolklitlab/alkiln/lib/scope.js:1714:21)
           at runMicrotasks ()
           at processTicksAndRejections (internal/process/task_queues.js:97:5)
           at async Object.funnel_the_answer (/var/www/.npm-global/lib/node_modules/@suffolklitlab/alkiln/lib/scope.js:1594:7)
           at async Object.setVariable (/var/www/.npm-global/lib/node_modules/@suffolklitlab/alkiln/lib/scope.js:1525:5)
           at async Object.setFields (/var/www/.npm-global/lib/node_modules/@suffolklitlab/alkiln/lib/scope.js:1965:24)
           at async /var/www/.npm-global/lib/node_modules/@suffolklitlab/alkiln/lib/steps.js:364:23
   - And I should not see the phrase "is the user of the form typically the Plaintiff" # ../var/www/.npm-global/lib/node_modules/@suffolklitlab/alkiln/lib/steps.js:501
   ✔ After # ../var/www/.npm-global/lib/node_modules/@suffolklitlab/alkiln/lib/steps.js:1103
```

Edit:
Will close https://github.com/SuffolkLITLab/ALKiln/issues/719

**Comment by BryceStevenWilley** [comment]
Note for us; uploads work in https://github.com/SuffolkLITLab/ALKiln/tree/sources_from_anywhere, but that branch stalled out a bit due to command line option discussions. [These lines specifically](https://github.com/SuffolkLITLab/ALKiln/blob/80d3cb953272a5d16369f549f0a50b307c5fc189/lib/run_cucumber.js#L19-L22) have the fix.

**Comment by plocket** [comment]
We already handle in-the-playground sources for getting the tests to begin with in the command line. This needs to be handled in `.uploadFiles()` in scope.js.

Unspoken so far: This needs to be an upstream fix in ALKiln.

Thanks for the catch, btw, though a shame it blocked you.

**Comment by plocket** [comment]
Bryce's comment is a great lead for the long-term v5 release fix, as well as this issue: https://github.com/SuffolkLITLab/ALKiln/issues/687

**Comment by plocket** [comment]
We've solved this for some situations. For applications like S3, we're going to handle it as described in https://github.com/SuffolkLITLab/ALKiln/issues/719:

> As per our [discussion in deep dive](https://docs.google.com/document/d/1WOW3IVWUEH82_nyAoy-nT6FM5N977YFoJnPB5ibYlD8/edit#heading=h.g5se2bv5k7dr), [this can be solved in ALKilnInThePlayground]. We can force the files to be cached in the `/tmp` folder with [code like that in the AL dashboard](https://github.com/SuffolkLITLab/docassemble-ALDashboard/blob/main/docassemble/ALDashboard/create_package.py#L14-L17). The arg `fix` is apparently the key to that. Then the files will be there for at least 2 hours. We might want to add that limitation to the docs at some point, though I'd be surprised if anyone actually runs into that limitation.
