### ISSUE TITLE
Require PRs to change the branch `main`

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-ALKilnInThePlayground#22]
Possibly helpful for security. This is in the repo settings. Who's an admin that can do that? @BryceStevenWilley ? @nonprofittechy ? No one will be able to push to `main` at that point without adjusting the settings.

**Comment by BryceStevenWilley** [comment]
Done! Didn't make any other things necessary to merge though (like approvals or tests passing), which matches how we run other AL repos
