### ISSUE TITLE
Logs are super verbose

### ISSUE THREAD

**Issue by michaelhofrichter** [SuffolkLITLab/docassemble-ALKilnInThePlayground#36]
Using Docassemble 1.4.88 and ALKiln 5.7.0, my docassemble.log size is now approaching 1.4 GB in size. I went looking at the log file briefly and the majority is linked to my docassemble testing account used exclusively for ALKiln. Could the docassemble logs be more limited by a env parameter or something?

**Comment by plocket** [comment]
I believe this ended up being a problem with old Projects not getting cleaned up and something going on with docassemble's way of handling that. If I'm wrong, feel free to reopen this issue.
